<!--

manifold-impact-analytics
https://github.com/braunsg/manifold-impact-analytics

Open source code for Manifold, an automated impact analytics and visualization platform developed by
Steven Braun.

COPYRIGHT (C) 2015 Steven Braun

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

A full copy of the license is included in LICENSE.md.

//////////////////////////////////////////////////////////////////////////////////////////
/////// About this file

Guide for merging Scopus author profiles

-->

<div class="page_header">Merging Scopus Author Profiles</div>

<div class="faq_header">About merging profiles</div>
<div class="faq_container">
	<a name="what-is-manifold"></a><div class="faq_subheader">What does "merging" mean?</div>
	<div class="faq_content">
	Every publication indexed in Scopus includes information about its listed authors. Using this data, Scopus automatically generates author profiles for any published name that provide an aggregated list of publications by a given author. By default, any published author has at least one such Scopus profile in this way; however, it is possible to merge multiple Scopus author profiles into a single profile, when necessary.
	</div>
</div>

<div class="faq_container">
	<a name="why-built"><div class="faq_subheader">Why would I need to do this?</div>
	<div class="faq_content">
Scopus is excellent at disambiguating common author names. For instance, if you have the last name “Johnson,” there are many other researchers in the world you could get confused with. However, Scopus uses accurate algorithms to ensure it has attributed the correct publications to the correct “Johnson” based on affiliation data and past publication history.<br><br>
Inevitably, these algorithms are not perfect, and occasionally publications will appear under multiple and/or erroneous author profiles in Scopus. While the publications may be correctly attributed to a given author, the author may be split into multiple profiles based on multiple differing affiliations.<br><br>
Scopus provides a mechanism for merging author profiles when this happens. This document will guide you through the process of merging your publications under a single author profile.
	</div>
</div>

<div class="faq_header">The merging process</div>
<div class="faq_container">
	<a name="what-is-manifold"></a><div class="faq_subheader">Identifying the error</div>
	<div class="faq_content">
	It is important to try and determine the source of the error, when possible, as this can help facilitate the appropriate merging process that is necessary. Any of the following are possible reasons for incomplete publication data for a given Scopus profile:
<ul>
	<li>An author may have all of their publications indexed in Scopus, but these publications are distributed across multiple (redundant) profiles that have been automatically generated by Scopus algorithms, making any single profile incomplete</li>
	<li>An author may have undergone a name change during the course of their career, resulting in their publications being split across multiple profiles with different names that actually belong to the same person</li>
	<li>An article that is presumed "missing" may actually exist in Scopus, but it is incorrectly attributed to another author with the same last name (especially in the case of authors with very common last names, such as "Johnson")</li>
	<li>An author’s Scopus profile may fully and accurately capture all of their publications, but the displayed affiliation is incorrect (i.e., not the University of Minnesota), meaning that external systems like Manifold are unable to correctly locate those profiles and their publication data</li>

</ul>
	When following the process outlined below, consider which of the above situations might best apply to you. This will help inform the specific kinds of steps you may need to follow.
	</div>
</div>
<div class="faq_container">
	<a name="what-is-manifold"></a><div class="faq_subheader">About the materials</div>
	<div class="faq_content">
	The steps described below were originally created for the University of Minnesota Libraries in the form of presentation slides. These slides can also be <b><a target="_blank" href="inc/resources/resources-content/merging-scopus-author-profiles.pdf">downloaded in PDF format</a></b> and are free for broad dissemination.<br><br>
	If you have any questions that are not answered here, please submit an inquiry through the <a href="resources.php?p=contact">contact form</a>. Otherwise, you may also seek personalized assistance through the <a target="_blank" href="http://help.elsevier.com/app/ask_scopus/p/8150">Scopus help desk</a>.
	</div>
	<div class="faq_content">
	<?php
	for($page = 1; $page <= 18; $page++) {
	?>
		<div class="resources_slide">
		<img src="inc/resources/resources-content/merging-scopus-profiles/merging-scopus-<?php echo $page; ?>.png">
		</div>
	<?php
	}
	?>
	</div>
</div>

